
#ifndef UTOPIA_CONSTANTS_H
#define UTOPIA_CONSTANTS_H

static const int MAX_RESPONSE_SIZE_IN_MS = 19000;
static const int MIN_RESPONSE_SIZE_IN_MS = 15;
static const int RANDOM_ITEM_COUNT = 100000;

#endif //UTOPIA_CONSTANTS_H